org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false
fabric.loom.dropNonIntermediateRootMethods=true

mod.id=eg_particle_interactions
mod.name=Particle Interactions
mod.description=A client side mod that adds particles to various interactions in the game that dont normally have particles.\
\n\
\n! IMPORTANT ! : If you are updating from an older version, your config will be reset! This should be the last time this will happen as the config system was rewritten in v0.9 to prevent this in the future\
\n\
\nNew in v0.9:\
\n\ - Updated to Minecraft 1.21.11\
\n\ - Rewritten the config system:\
\n\    - YACL is now an optional dependency\
\n\    - Only non-default config values are saved now\
\n\    - Allows for better config updating in the future (no more resetting the config every update!)\
\n\    - All previous config values will be reset, however, the config file from older versions will remain untouched\
\n\    - Some default config values have been fixed\
\n\ - Added toggles to disable all block placing or breaking particles\
\n\ - Lava bubble pop particles now match the lava height more closely\
\n\ - Adjusted Redstone Dust and Redstone Interaction Dust particles to look closer to vanilla redstone particles\
\n\ - A bunch of internal refactors have been made this update, do make sure to report any issues you find!
mod.group=games.enchanted
mod.version=0.9.3
mod.license=CC BY-NC 4.0
mod.source_url=https://github.com/Enchanted-Games/block-place-particles
mod.issue_tracker=https://github.com/Enchanted-Games/block-place-particles/issues
mod.icon=assets/eg_particle_interactions/icon.png

deps.minecraft=[VERSIONED]
dep_str.minecraft=[VERSIONED]

deps.fabric-loader=0.18.4
dep_str.fabric-loader=>=0.18

deps.fabric-api=[VERSIONED]
dep_str.fabric-api=[VERSIONED]

deps.neoforge=[VERSIONED]

publish.dry_run=true
# Uncomment and enter modrinth or curseforge project ids to enable publishing
publish.modrinth=xFCYuAs8
publish.curseforge=1235471
#publish.additionalVersions=[VERSIONED]