org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false
fabric.loom.dropNonIntermediateRootMethods=true

publish.dry_run=true
# Uncomment and enter modrinth or curseforge project ids to enable publishing
publish.modrinth=xFCYuAs8
publish.curseforge=1235471
#publish.additionalVersions=[VERSIONED]