modLoader="javafml"
loaderVersion="[2,)"
license="${license}"
issueTrackerURL="${issue_tracker}"
displayURL="${website_url}"

[[mods]]
modId="${id}"
version="${version}"
displayName="${name}"
logoFile="${icon}"
logoBlur=false
authors="Enchanted_Games"
description='''
${description}
'''

[[mixins]]
config="${id}.mixins.json"

[[mixins]]
config="${id}.26_2.mixins.json"

[[mixins]]
config="mod_compat.${id}.mixins.json"

[[dependencies.${id}]]
modId="minecraft"
type="required"
versionRange="${minecraft}"
side="CLIENT"
