deps.core.mc.version_range=1.21.10
deps.core.mc.compatible_range=1.21.10
publish_acceptable_mc_versions=1.21.10

# https://fabricmc.net/develop/
deps.api.fabric=0.135.0+1.21.10
# https://parchmentmc.org/docs/getting-started
deps.parchment.mc_version=1.21.8
deps.parchment.version=2025.09.14

# modmenu
#deps.api.modmenu=15.0.0
# yacl
deps.api.yacl=3.8.0+1.21.9-fabric

loom.platform=fabric