deps.core.mc.version_range=1.21.11-rc3
deps.core.mc.compatible_range=1.21.11-beta.3
publish_acceptable_mc_versions=1.21.11-rc3

# https://fabricmc.net/develop/
deps.api.fabric=0.139.4+1.21.11
# https://parchmentmc.org/docs/getting-started
deps.parchment.mc_version=1.21.10
deps.parchment.version=2025.10.12

# modmenu
deps.api.modmenu.componly=true
deps.api.modmenu=16.0.0-rc.1
# yacl
deps.api.yacl=3.8.1+1.21.11-fabric

loom.platform=fabric