deps.core.mc.version_range=1.21.1 1.21.1

# https://fabricmc.net/develop/
deps.api.fabric=0.116.3+1.21.1
# https://parchmentmc.org/docs/getting-started
deps.parchment.mc_version=1.21.1
deps.parchment.version=2024.11.17

# modmenu
deps.api.modmenu=11.0.3
# yacl
deps.api.yacl=3.7.1+1.21.1-fabric

loom.platform=fabric