deps.core.mc.version_range=1.21.8
deps.core.mc.compatible_range=1.21.6
publish.acceptable_mc_versions=1.21.6

# https://projects.neoforged.net/neoforged/neoforge
deps.core.neoforge.version_range=21.8.2-beta
# https://parchmentmc.org/docs/getting-started
deps.parchment.mc_version=1.21.6
deps.parchment.version=2025.06.29

# yacl
deps.api.yacl=3.7.1+1.21.6-neoforge

loom.platform=neoforge