modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "${license}"
issueTrackerURL = "${mod_issues}"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
#updateJSONURL = "" #optional (see https://docs.neoforged.net/docs/misc/updatechecker/)
displayURL = "${mod_homepage}"
logoFile = "assets/${mod_id}/icon.png"
credits = "${credits}"
authors = "${mod_author}"
description = '''${description}'''

[[mixins]]
config = "${mod_id}.mixins.json"
[[mixins]]
config = "${mod_id}.neoforge.mixins.json"

[[dependencies.${mod_id}]]
modId = "neoforge"
type="required"
versionRange = "${neoforge_loader_version_range}"
ordering = "NONE"
side = "BOTH"
[[dependencies.${mod_id}]]
modId = "minecraft"
type="required"
versionRange = "${minecraft_neoforge_version_range}"
ordering = "NONE"
side = "BOTH"